services:
  nns-backend:
    image: lequocuy/nns-backend:latest
    container_name: nns-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=nns-database;Database=nns-database;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true"
    build:
      context: .
      dockerfile: nns-backend/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - nns-database

  nns-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nns-database
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1435:1433"
    volumes:
      - ./.containers/nongnghiepso-db:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup
